### ISSUE TITLE
Entry creation via a form in 1.0.1

### ISSUE THREAD

**Issue by animaux** [symphonists/association_field#22] opened 2016-05-17 12:19 UTC
On Symphony `2.6.7` I get an error when trying to create an entry via a frontend form/event. This works fine in `1.0.0beta` but after updating to `1.0.1` the following error is thrown after submit:

```
Fatal error: Call to a member function getContext() on null in /…/symphony/lib/toolkit/class.field.php on line 739
```

There quite a few changes regarding context in from `1.0.0beta` to `1.0.1` in `field.association.php`. So I guess the problem resides somwhere here.

**Comment by nilshoerrmann** [comment] 2017-06-05 06:55
Just experienced this as well: Did you find a fix for this issue, @animaux?

**Comment by animaux** [comment] 2017-06-05 07:09
I don’t remember … I would guess I might have gone back to `1.0.0beta` for that particular installation.

**Comment by nilshoerrmann** [comment] 2017-06-05 07:20
Thanks, Alex.

I think I just found the culprit: the source of the issue is the Tracker extension which calls the function `prepareTableValue` when it shouldn't.

**Comment by animaux** [comment] 2017-06-05 07:32
That sounds familiar too `:)`

**Closed** 2017-06-05 08:50 UTC

**Comment by animaux** [comment] 2017-06-05 09:04
👍 Danke Nils!

**Comment by nilshoerrmann** [comment] 2017-06-05 11:45
Keine Ursache!
